[package]
name = "aztec_semaphore"
type = "contract"
authors = ["HashCloak"]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.5", directory="noir-projects/aztec-nr/aztec" }
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.5", directory="noir-projects/aztec-nr/easy-private-state"}